spring:
    profiles:
        active: mysql
        default: true
    datasource:
        url: jdbc:mysql://localhost:3306/dating?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: L0zRQBFNx6oYVO1zyZUxMHjTM++9r1qv
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: mysql
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    main:
        log-startup-info: false
---
spring:
    profiles: h2
    liquibase:
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.xml
    datasource:
        url: jdbc:h2:mem:dating;DB_CLOSE_DELAY=-1
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    main:
        log-startup-info: false
    h2:
        console:
            enabled: true
            path: /h2-console
            settings.trace: false
            settings.web-allow-others: false